"""empty message

Revision ID: 0a1cb394e461
Revises: 50cee36fe7fa
Create Date: 2019-07-22 14:24:32.931541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1cb394e461'
down_revision = '50cee36fe7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transaction', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bank_transaction_category'), 'bank_transaction', ['category'], unique=False)
    op.add_column('cash_transaction', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_cash_transaction_category'), 'cash_transaction', ['category'], unique=False)
    op.add_column('pay_app_transaction', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pay_app_transaction_category'), 'pay_app_transaction', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_app_transaction_category'), table_name='pay_app_transaction')
    op.drop_column('pay_app_transaction', 'category')
    op.drop_index(op.f('ix_cash_transaction_category'), table_name='cash_transaction')
    op.drop_column('cash_transaction', 'category')
    op.drop_index(op.f('ix_bank_transaction_category'), table_name='bank_transaction')
    op.drop_column('bank_transaction', 'category')
    # ### end Alembic commands ###
