"""3 transasction tables and relations

Revision ID: 17b6dbafd0cd
Revises: f6ea91d30765
Create Date: 2019-07-07 18:22:43.405224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b6dbafd0cd'
down_revision = 'f6ea91d30765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transaction_amount'), 'bank_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transaction_debit'), 'bank_transaction', ['debit'], unique=False)
    op.create_table('cash_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transaction_amount'), 'cash_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_cash_transaction_debit'), 'cash_transaction', ['debit'], unique=False)
    op.create_table('pay_app_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_app_transaction_amount'), 'pay_app_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_pay_app_transaction_debit'), 'pay_app_transaction', ['debit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_app_transaction_debit'), table_name='pay_app_transaction')
    op.drop_index(op.f('ix_pay_app_transaction_amount'), table_name='pay_app_transaction')
    op.drop_table('pay_app_transaction')
    op.drop_index(op.f('ix_cash_transaction_debit'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_amount'), table_name='cash_transaction')
    op.drop_table('cash_transaction')
    op.drop_index(op.f('ix_bank_transaction_debit'), table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_amount'), table_name='bank_transaction')
    op.drop_table('bank_transaction')
    # ### end Alembic commands ###
