"""empty message

Revision ID: 2783cf5d5271
Revises: 2ffa80102330
Create Date: 2019-07-07 17:52:11.811932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2783cf5d5271'
down_revision = '2ffa80102330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_bankBalance'), 'user', ['bankBalance'], unique=False)
    op.create_index(op.f('ix_user_payappBalance'), 'user', ['payappBalance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payappBalance'), table_name='user')
    op.drop_index(op.f('ix_user_bankBalance'), table_name='user')
    # ### end Alembic commands ###
