"""empty message

Revision ID: 9fb5359fb1d3
Revises: 731f0dcaa96d
Create Date: 2019-08-11 18:34:48.188653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb5359fb1d3'
down_revision = '731f0dcaa96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currency')
    # ### end Alembic commands ###
