"""empty message

Revision ID: cac6632f7e2a
Revises: 
Create Date: 2019-07-10 22:24:26.445996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac6632f7e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cashBalance', sa.Integer(), nullable=True),
    sa.Column('bankBalance', sa.Integer(), nullable=True),
    sa.Column('payappBalance', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bankBalance'), 'user', ['bankBalance'], unique=False)
    op.create_index(op.f('ix_user_cashBalance'), 'user', ['cashBalance'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_payappBalance'), 'user', ['payappBalance'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transaction_amount'), 'bank_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transaction_date'), 'bank_transaction', ['date'], unique=False)
    op.create_index(op.f('ix_bank_transaction_debit'), 'bank_transaction', ['debit'], unique=False)
    op.create_index(op.f('ix_bank_transaction_description'), 'bank_transaction', ['description'], unique=False)
    op.create_table('cash_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transaction_amount'), 'cash_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_cash_transaction_date'), 'cash_transaction', ['date'], unique=False)
    op.create_index(op.f('ix_cash_transaction_debit'), 'cash_transaction', ['debit'], unique=False)
    op.create_index(op.f('ix_cash_transaction_description'), 'cash_transaction', ['description'], unique=False)
    op.create_table('pay_app_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('debit', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_app_transaction_amount'), 'pay_app_transaction', ['amount'], unique=False)
    op.create_index(op.f('ix_pay_app_transaction_date'), 'pay_app_transaction', ['date'], unique=False)
    op.create_index(op.f('ix_pay_app_transaction_debit'), 'pay_app_transaction', ['debit'], unique=False)
    op.create_index(op.f('ix_pay_app_transaction_description'), 'pay_app_transaction', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_app_transaction_description'), table_name='pay_app_transaction')
    op.drop_index(op.f('ix_pay_app_transaction_debit'), table_name='pay_app_transaction')
    op.drop_index(op.f('ix_pay_app_transaction_date'), table_name='pay_app_transaction')
    op.drop_index(op.f('ix_pay_app_transaction_amount'), table_name='pay_app_transaction')
    op.drop_table('pay_app_transaction')
    op.drop_index(op.f('ix_cash_transaction_description'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_debit'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_date'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_amount'), table_name='cash_transaction')
    op.drop_table('cash_transaction')
    op.drop_index(op.f('ix_bank_transaction_description'), table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_debit'), table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_date'), table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_amount'), table_name='bank_transaction')
    op.drop_table('bank_transaction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_payappBalance'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cashBalance'), table_name='user')
    op.drop_index(op.f('ix_user_bankBalance'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
