"""empty message

Revision ID: cf1da9a0aac8
Revises: 17b6dbafd0cd
Create Date: 2019-07-09 17:42:35.427912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1da9a0aac8'
down_revision = '17b6dbafd0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transaction', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bank_transaction_description'), 'bank_transaction', ['description'], unique=False)
    op.add_column('cash_transaction', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_cash_transaction_description'), 'cash_transaction', ['description'], unique=False)
    op.add_column('pay_app_transaction', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pay_app_transaction_description'), 'pay_app_transaction', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_app_transaction_description'), table_name='pay_app_transaction')
    op.drop_column('pay_app_transaction', 'description')
    op.drop_index(op.f('ix_cash_transaction_description'), table_name='cash_transaction')
    op.drop_column('cash_transaction', 'description')
    op.drop_index(op.f('ix_bank_transaction_description'), table_name='bank_transaction')
    op.drop_column('bank_transaction', 'description')
    # ### end Alembic commands ###
