"""empty message

Revision ID: d25fde9e018d
Revises: 5f96c4d203cd
Create Date: 2019-07-10 19:30:02.408340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25fde9e018d'
down_revision = '5f96c4d203cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transaction', sa.Column('date', sa.String(), nullable=True))
    op.create_index(op.f('ix_bank_transaction_date'), 'bank_transaction', ['date'], unique=False)
    op.add_column('cash_transaction', sa.Column('date', sa.String(), nullable=True))
    op.create_index(op.f('ix_cash_transaction_date'), 'cash_transaction', ['date'], unique=False)
    op.add_column('pay_app_transaction', sa.Column('date', sa.String(), nullable=True))
    op.create_index(op.f('ix_pay_app_transaction_date'), 'pay_app_transaction', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_app_transaction_date'), table_name='pay_app_transaction')
    op.drop_column('pay_app_transaction', 'date')
    op.drop_index(op.f('ix_cash_transaction_date'), table_name='cash_transaction')
    op.drop_column('cash_transaction', 'date')
    op.drop_index(op.f('ix_bank_transaction_date'), table_name='bank_transaction')
    op.drop_column('bank_transaction', 'date')
    # ### end Alembic commands ###
