"""empty message

Revision ID: f6ea91d30765
Revises: 2783cf5d5271
Create Date: 2019-07-07 17:52:39.999682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ea91d30765'
down_revision = '2783cf5d5271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cashBalance', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_cashBalance'), 'user', ['cashBalance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cashBalance'), table_name='user')
    op.drop_column('user', 'cashBalance')
    # ### end Alembic commands ###
